version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser      
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: mydatabase    
    ports:
      - "5433:5432"               

